# version: 2
# updates:
#   - package-ecosystem: github-actions
#     directory: /
#     schedule:
#       interval: daily

version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule: daily