name: Annotation
on: workflow_dispatch
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::error::Error messages"
      - run: echo "::warning::Warning messages"
      - run: echo "::Notice::Notice messages"