name: Call Reusable Workflows

on: pull_request

jobs:
  call:
    uses: ./.github/workflows/reusable_workflows.yml
    with:
      version: 1.0.0
      push: true

  print:
    needs: call
    runs-on: ubuntu-latest
    steps:
      - run: echo "Result> ${MESSAGE}"
        env:
          MESSAGE: ${{ needs.call.outputs.digest }}
