name: Manual
on:
  workflow_dispach:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheeful word prease!

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"