name: Reusable Workflows

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: タグ用のバージョン名 例:1.0.0
      push:
        type: boolean
        required: true
        default: true
        description: dockerイメージをプッシュするか
    
    outputs:
      digest:
        value: ${{ jobs.publish.outputs.digest }}
        description: pushed image digest (sha256)

env:
  IMAGE_NAME: reusable_workflow

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3 # GitHub Container Registryへのログイン
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5 # コンテナメタデータの生成
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=v${{ inputs.version }}
            type=raw,value=latest
      - uses: docker/build-push-action@v5 # コンテナイメージのbuild(+push)
        id: build-push
        with:
          push: ${{ inputs.push }}
          context: docker/practice_reusable_workflow/
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    outputs:
      digest: ${{ steps.build-push.outputs.digest }} # ビルド済みのコンテナ情報を返却
      